--Database Name
CREATE DATABASE IF NOT EXISTS future_fs CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE future_fs;

--Contacts Table
CREATE TABLE IF NOT EXISTS contacts (
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  phone VARCHAR(50),
  message TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


--Blogs Table
CREATE TABLE IF NOT EXISTS blogs (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  content TEXT NOT NULL,
  published_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


--Projects Table
CREATE TABLE IF NOT EXISTS projects (
  title VARCHAR(255) NOT NULL,
  language VARCHAR(100) NOT NULL,
  content TEXT NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;